### ISSUE TITLE
cannot find module

### ISSUE THREAD

**Issue by ajeema** [josepaiva94/starter-fastapi-celery#1]
Hello, thank you for this starter script. I'm trying to add a python package (ffmpeg-python). I've tried adding it in the docker file, in poetry, as an app level module, and no matter what it says it cannot find the module from the app (FastAPI). I tried to sh into the shell and run pip in the docker container. verified that it works by calling it direction in Python console and it does. So why cant the app (FastAPI) find the module?

**Comment by josepaiva94** [comment]
Hi, do you have a repository reproducing this issue?

**Comment by ajeema** [comment]
It's essentially your code with import ffmpeg in main.py. No matter what I do it will not find that module. I even changed the base image to one that I know has it installed on and still nothing.

**Comment by ajeema** [comment]
Resolved it by declairing the ENV of the pythonpath in the docker file. i.e (ENV PYTHONPATH "${PYTHONPATH}:/usr/local/lib/python3.9/site-packages/"
)

this seems to have solved the problem but unsure why the pip packages installed during build didn't get added to the path. It is because poetry is setting up a virtualenv and these packages don't get included in that?

**Comment by josepaiva94** [comment]
I have  made a working sample https://github.com/josepaiva94/starter-fastapi-celery/tree/ffmpeg
